# Notebook 04 — Closed-Loop Dual-Track Generation (With WQB)

**Goal**: Run the full dual-track orchestration loop:
```
[Explorer]  Idea → Synthesis → Validate → Novelty(strict)  ──┐
                                                               ├─► WQB Simulate → Qualify → Reflect
[Skeleton]  SkeletonRegistry → SkeletonAgent → Validate ──────┘         │
                                                                         ▼
                                                              SkeletonExtractor → SkeletonRegistry
```

**Three `track_mode` options:**
- `"explorer_only"` — only the free-exploration LLM track (original behavior)
- `"skeleton_only"` — only the controlled skeleton-variation track
- `"hybrid"` *(default)* — both tracks, budget split by TrackBandit (UCB)

**Requires**: Notebooks 01–03 completed. WQB credentials set in `.env`.

⚠️ **WQB API quota**: each expression costs one simulation. Start with `n_rounds=1`.

In [1]:
import asyncio
import nest_asyncio
nest_asyncio.apply()

from alpha_agent.config import settings
from alpha_agent.knowledge.vector_store import VectorStore
from alpha_agent.knowledge.alpha_memory import AlphaMemory
from alpha_agent.knowledge.skeleton_registry import SkeletonRegistry
from alpha_agent.data.operator_kb import OperatorKB
from alpha_agent.data.wqb_client import WQBClient
from alpha_agent.engine.orchestrator import Orchestrator
from alpha_agent.search.bandit import DirectionBandit
from alpha_agent.search.track_bandit import TrackBandit

store    = VectorStore()
memory   = AlphaMemory()
skeleton_db_path = settings.duckdb_path.with_name("skeleton_registry.db")
registry = SkeletonRegistry(db_path=skeleton_db_path)
kb       = OperatorKB()

print("AlphaMemory DB:", settings.duckdb_path)
print("SkeletonRegistry DB:", skeleton_db_path)
print("SkeletonRegistry status:", registry.stats())

mem_status = memory.status()
print("AlphaMemory status:", mem_status)
if mem_status.get("read_only"):
    raise RuntimeError(
        "AlphaMemory is read-only in this kernel (likely DB lock by another notebook/process). "
        "Please stop other kernels using alpha_memory.db and rerun this cell."
    )

/Users/weiyanguang/vscodeprojects/WorldQuant-Brain-Alpha/myenv/lib/python3.11/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm, trange

AlphaMemory DB: /Users/weiyanguang/vscodeprojects/WorldQuant-Brain-Alpha/data/alpha_memory.db
SkeletonRegistry DB: /Users/weiyanguang/vscodeprojects/WorldQuant-Brain-Alpha/data/skeleton_registry.db
SkeletonRegistry status: {'total': 0, 'active': 0, 'instances': 0}
AlphaMemory status: {'path': '/Users/weiyanguang/vscodeprojects/WorldQuant-Brain-Alpha/data/alpha_memory.db', 'read_only': False, 'ephemeral': False, 'lock_message': ''}

## 1. Configure the run

In [2]:
# ─── Configuration ────────────────────────────────────────────────────────
# DIRECTION  = "short-term price reversal with liquidity adjustment"
DIRECTION = "medium-horizon reversal with liquidity and volatility normalization"
DATASET    = "pv1"
UNIVERSE   = "TOP1000"
N_ROUNDS   = 50        # start small! increase after validating setup
IDEAS_PER_ROUND   = 8
VARIANTS_PER_IDEA = 4
EXPLORE_BIAS = 0.3   # 0=explore, 1=exploit
AUTO_SUBMIT  = False  # set True to auto-submit qualified alphas
DRY_RUN      = False  # True = skip WQB (for testing prompt quality)

# ─── Track mode ───────────────────────────────────────────────────────────
# "hybrid"        → TrackBandit splits budget between Explorer + Skeleton
# "explorer_only" → only free-exploration LLM (original behavior)
# "skeleton_only" → only SkeletonAgent (needs seeds in registry first)
TRACK_MODE = "hybrid"
# ──────────────────────────────────────────────────────────────────────────

## 2. (Optional) Use Bandit to auto-select direction

In [3]:
# Uncomment to let the bandit choose the direction automatically
# bandit = DirectionBandit(memory)
# DIRECTION = bandit.select()
# print(f"Bandit selected direction: {DIRECTION}")

print(f"Direction: {DIRECTION}")
print(f"Dataset:   {DATASET} / {UNIVERSE}")
print(f"Rounds:    {N_ROUNDS}")
print(f"Dry run:   {DRY_RUN}")

Direction: medium-horizon reversal with liquidity and volatility normalization
Dataset:   pv1 / TOP1000
Rounds:    50
Dry run:   False

## 3. Run the orchestration loop

In [4]:
async def run_pipeline():
    async with WQBClient() as client:
        orch = Orchestrator(
            client=client,
            vector_store=store,
            alpha_memory=memory,
            skeleton_registry=registry,
            operator_kb=kb,
            auto_submit=AUTO_SUBMIT,
        )
        reports = await orch.run(
            direction=DIRECTION,
            dataset=DATASET,
            universe=UNIVERSE,
            n_rounds=N_ROUNDS,
            ideas_per_round=IDEAS_PER_ROUND,
            variants_per_idea=VARIANTS_PER_IDEA,
            explore_exploit_bias=EXPLORE_BIAS,
            dry_run=DRY_RUN,
            track_mode=TRACK_MODE,
        )
    return reports

reports = asyncio.run(run_pipeline())

──────────────── Round 1/50 — medium-horizon reversal with liquidity and volatility normalization ─────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (22)

  [01] -ts_delta(returns, 40) * inverse(ts_zscore(returns, 20) + 2) * inverse(ts_mean(volume, 40) + 1e-6)

  [02] reverse(ts_delta(returns, 50)) * inverse(ts_std_dev(returns, 10) + ts_mean(volume, 50))

  [03] -ts_delta(returns, 30) * inverse(signed_power(ts_std_dev(returns, 15), 0.5) * ts_mean(volume, 30))

  [04] normalize(divide(ts_delta(log(close), 90), ts_mean(cap, 10)))

  [05] ts_scale(divide(ts_sum(returns, 90), ts_mean(cap, 20)), 30)

  [06] group_neutralize(ts_rank(returns, 90), bucket(rank(cap), range='0,1,0.1'))

  [07] normalize(multiply(ts_zscore(returns, 60), inverse(cap)))

  [08] multiply(reverse(ts_sum(returns, 30)), ts_delta(volume, 5))

  [09] multiply(reverse(ts_sum(returns, 40)), ts_delta(log(volume), 3))

  [10] normalize(reverse(ts_quantile(returns, 20, driver='gaussian')))

  [11] normalize(reverse(ts_zscore(returns, 20)))

  [12] zscore(reverse(ts_mean(returns, 20)))

  [13] normalize(group_neutralize(ts_delta(log(close), 60), subindustry))

  [14] zscore(group_neutralize(subtract(ts_delta(close, 60), ts_delta(ts_mean(close, 5), 60)), subindustry))

  [15] normalize(group_neutralize(ts_regression(ts_delta(close, 60), ts_delta(vwap, 60), 60, rettype=0),
subindustry))

  [16] winsorize(group_neutralize(ts_av_diff(ts_delta(close, 60), 20), subindustry), std=4)

  [17] divide(add(-ts_sum(ts_delay(returns, 1), 5), -ts_sum(ts_delay(returns, 1), 60)), ts_mean(volume, 20))

  [18] divide(-add(ts_sum(returns, 5), multiply(2, ts_sum(returns, 60))), multiply(volume, ts_std_dev(returns, 5)))

  [19] multiply(-add(ts_delta(close, 5), ts_delta(close, 60)), inverse(multiply(volume, ts_mean(volume, 60))))

  [20] divide(ts_mean(subtract(open, close), 10), ts_std_dev(returns, 20))

  [21] divide(ts_sum(subtract(open, close), 10), ts_std_dev(returns, 10))

  [22] multiply(reverse(normalize(ts_sum(returns, 10))), normalize(ts_delta(ts_std_dev(returns, 20), 5)))

Simulating 22 expressions on WQB...

2026-04-22 01:35:00 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full='-ts_delta(returns, 40) * inverse(ts_zscore(returns, 20) + 2) * inverse(ts_mean(volume, 40) + 1e-6)'

Reflecting on results...

                                        Round 1 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                   1 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                  22 │
│ simulated             │                                                                  21 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                  21 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                         3640.740633 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 2/50 — medium-horizon reversal with liquidity and volatility normalization ─────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (6)

  [01] multiply(divide(ts_sum(if_else(returns>0, returns, 0), 20), add(ts_sum(if_else(returns<0, abs(returns), 0),
20), 1e-6)), reverse(ts_sum(returns, 60)))

  [02] multiply(divide(ts_sum(if_else(returns>0, returns, 0), 10), add(ts_sum(if_else(returns<0, abs(returns), 0),
10), 1e-6)), reverse(ts_sum(returns, 40)))

  [03] multiply(divide(ts_sum(if_else(ts_av_diff(returns, 20)>0, ts_av_diff(returns, 20), 0), 20),
add(ts_sum(if_else(ts_av_diff(returns, 20)<0, abs(ts_av_diff(returns, 20)), 0), 20), 1e-6)),
reverse(ts_delta(close, 60)))

  [04] reverse(ts_sum((open - ts_delay(close, 1)) / ts_delay(close, 1), 20))

  [05] normalize(reverse(ts_mean((open - ts_delay(close, 1)) / ts_delay(close, 1), 15)))

  [06] reverse(ts_sum(if_else((open - ts_delay(close, 1)) / ts_delay(close, 1) < 0, (open - ts_delay(close, 1)) /
ts_delay(close, 1), 0), 25))

Simulating 6 expressions on WQB...

2026-04-22 02:32:56 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full='multiply(divide(ts_sum(if_else(returns>0, returns, 0), 20), add(ts_sum(if_else(returns<0, abs(returns), 0), 20), 1e-6)), reverse(ts_sum(returns, 60)))'
2026-04-22 02:33:09 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full='multiply(divide(ts_sum(if_else(returns>0, returns, 0), 10), add(ts_sum(if_else(returns<0, abs(returns), 0), 10), 1e-6)), reverse(ts_sum(returns, 40)))'
2026-04-22 02:33:22 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full='multiply(divide(ts_sum(if_else(ts_av_diff(returns, 20)>0, ts_av_diff(returns, 20), 0), 20), add(ts_sum(if_else(ts_av_diff(returns, 20)<0, abs(ts_av_diff(returns, 20)), 0), 20), 1e-6)), reverse(ts_delta(close, 60)))'

Reflecting on results...

                                        Round 2 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                   2 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   6 │
│ simulated             │                                                                   3 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   3 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                           789.93561 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 3/50 — medium-horizon reversal with liquidity and volatility normalization ─────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (2)

  [01] divide(reverse(ts_zscore(ts_sum(returns, 15), 30)), log(cap))

  [02] reverse(ts_zscore(divide(abs(subtract(divide(close, open), 1)), ts_std_dev(divide(subtract(high, low),
open), 5)), 15))

Simulating 2 expressions on WQB...

Reflecting on results...

                                        Round 3 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                   3 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   2 │
│ simulated             │                                                                   2 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   2 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          708.227617 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 4/50 — medium-horizon reversal with liquidity and volatility normalization ─────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 30 expressions

No expressions passed novelty filter.

                                        Round 4 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                   4 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  30 │
│ expressions_generated │                                                                  30 │
│ after_validation      │                                                                  30 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          324.262349 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 5/50 — medium-horizon reversal with liquidity and volatility normalization ─────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (4)

  [01] divide(ts_av_diff(ts_sum(subtract(close, open), 15), 15), sharesout)

  [02] reverse(divide(ts_delta(subtract(high, low), 20), cap))

  [03] reverse(divide(ts_delta(subtract(high, low), 10), cap))

  [04] reverse(divide(ts_delta(subtract(divide(high, close), divide(low, close)), 20), cap))

Simulating 4 expressions on WQB...

Reflecting on results...

                                        Round 5 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                   5 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   4 │
│ simulated             │                                                                   4 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   4 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          870.271694 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 6/50 — medium-horizon reversal with liquidity and volatility normalization ─────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (5)

  [01] reverse(ts_sum(returns, 40)) * cap

  [02] normalize(-ts_corr(close, volume, 20))

  [03] normalize(multiply(reverse(ts_sum(returns,30)), max(if_else(subtract(kth_element(returns,30,15),
kth_element(returns,30,8)) > 1e-10, divide(subtract(kth_element(returns,30,23), kth_element(returns,30,15)),
subtract(kth_element(returns,30,15), kth_element(returns,30,8))), 0), 0)), useStd=true)

  [04] normalize(multiply(reverse(ts_sum(returns,20)), max(if_else(subtract(kth_element(returns,30,15),
kth_element(returns,30,3)) > 1e-10, divide(subtract(kth_element(returns,30,27), kth_element(returns,30,15)),
subtract(kth_element(returns,30,15), kth_element(returns,30,3))), 0), 0)), useStd=true)

  [05] normalize(multiply(reverse(ts_sum(returns,30)), max(divide(add(add(kth_element(returns,30,30),
kth_element(returns,30,29)), kth_element(returns,30,28)), 3), 0)), useStd=true)

Simulating 5 expressions on WQB...

2026-04-22 03:23:42 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full='normalize(multiply(reverse(ts_sum(returns,30)), max(if_else(subtract(kth_element(returns,30,15), kth_element(returns,30,8)) > 1e-10, divide(subtract(kth_element(returns,30,23), kth_element(returns,30,15)), subtract(kth_element(returns,30,15), kth_element(returns,30,8))), 0), 0)), useStd=true)'
2026-04-22 03:23:55 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full='normalize(multiply(reverse(ts_sum(returns,20)), max(if_else(subtract(kth_element(returns,30,15), kth_element(returns,30,3)) > 1e-10, divide(subtract(kth_element(returns,30,27), kth_element(returns,30,15)), subtract(kth_element(returns,30,15), kth_element(returns,30,3))), 0), 0)), useStd=true)'
2026-04-22 03:25:00 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full='normalize(multiply(reverse(ts_sum(returns,30)), max(divide(add(add(kth_element(returns,30,30), kth_element(returns,30,29)), kth_element(returns,30,28)), 3), 0)), useStd=true)'

Reflecting on results...

                                        Round 6 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                   6 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   5 │
│ simulated             │                                                                   2 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   2 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          804.020176 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 7/50 — medium-horizon reversal with liquidity and volatility normalization ─────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (1)

  [01] normalize(multiply(reverse(ts_sum(returns, 60)), max(ts_mean(power(subtract(returns, ts_mean(returns, 20)),
3), 20), 0)))

Simulating 1 expressions on WQB...

Reflecting on results...

                                        Round 7 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                   7 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   1 │
│ simulated             │                                                                   1 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   1 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                           540.22561 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 8/50 — medium-horizon reversal with liquidity and volatility normalization ─────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                        Round 8 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                   8 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          305.583408 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 9/50 — medium-horizon reversal with liquidity and volatility normalization ─────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                        Round 9 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                   9 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          348.484541 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 10/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 10 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  10 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          394.115372 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 11/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 29 expressions

Expressions after novelty filter (4)

  [01] multiply(group_zscore(reverse(ts_mean(returns, 40)), subindustry), group_scale(volume, subindustry))

  [02] multiply(reverse(returns), cap, if_else(ts_quantile(returns, 20, 0.9) > ts_mean(returns, 20), rank(cap), 1))

  [03] multiply(reverse(ts_delta(returns, 3)), cap, power(rank(cap), ts_scale(ts_quantile(returns, 40, 0.75), 10)))

  [04] multiply(subtract(0.5, ts_scale(close, 20)), inverse(adv20))

Simulating 4 expressions on WQB...

2026-04-22 03:59:42 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full='multiply(reverse(returns), cap, if_else(ts_quantile(returns, 20, 0.9) > ts_mean(returns, 20), rank(cap), 1))'
2026-04-22 03:59:49 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full='multiply(reverse(ts_delta(returns, 3)), cap, power(rank(cap), ts_scale(ts_quantile(returns, 40, 0.75), 10)))'

Reflecting on results...

                                       Round 11 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  11 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  29 │
│ expressions_generated │                                                                  29 │
│ after_validation      │                                                                  29 │
│ after_novelty_filter  │                                                                   4 │
│ simulated             │                                                                   2 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   2 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          682.993373 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 12/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (1)

  [01] if_else(ts_max(high,15)-ts_min(low,15) > 0, reverse(ts_delta(close,10)/(ts_max(high,15)-ts_min(low,15))), 0)

Simulating 1 expressions on WQB...

2026-04-22 04:09:08 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full='if_else(ts_max(high,15)-ts_min(low,15) > 0, reverse(ts_delta(close,10)/(ts_max(high,15)-ts_min(low,15))), 0)'

Reflecting on results...

                                       Round 12 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  12 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   1 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          305.210313 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 13/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (1)

  [01] reverse(ts_rank(ts_scale(divide(subtract(close, open), open), 40), 40))

Simulating 1 expressions on WQB...

Reflecting on results...

                                       Round 13 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  13 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   1 │
│ simulated             │                                                                   1 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   1 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                           538.66195 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 14/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (1)

  [01] if_else(ts_delta(divide(volume, cap), 15) < 0, ts_rank(returns, 10), 0)

Simulating 1 expressions on WQB...

Reflecting on results...

                                       Round 14 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  14 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   1 │
│ simulated             │                                                                   1 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   1 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          493.259648 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 15/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (2)

  [01] normalize(winsorize(divide(ts_regression(ts_sum(returns,5), ts_std_dev(returns,30),20,rettype=2), cap),
std=4), useStd=true)

  [02] zscore(divide(ts_regression(ts_sum(returns,60), ts_mean(divide(subtract(high,low),vwap),20),120,rettype=2),
cap))

Simulating 2 expressions on WQB...

Reflecting on results...

                                       Round 15 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  15 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   2 │
│ simulated             │                                                                   2 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   2 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                           622.11012 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 16/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 16 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  16 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          299.378742 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 17/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 17 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  17 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          273.856673 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 18/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (2)

  [01] reverse(ts_delta(close, 25)) * signed_power(ts_rank(close, 25), -1) * rank(inverse(cap))

  [02] add(subtract(0.5, ts_rank(ts_sum(returns, 5), 20)), subtract(0.5, ts_rank(ts_sum(returns, 60), 60)))

Simulating 2 expressions on WQB...

Reflecting on results...

                                       Round 18 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  18 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   2 │
│ simulated             │                                                                   2 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   2 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          612.106674 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 19/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 19 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  19 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                           252.68748 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 20/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (1)

  [01] zscore(multiply(ts_quantile(ts_delta(close, 8), 15), ts_rank(divide(volume, ts_mean(volume, 10)), 10)))

Simulating 1 expressions on WQB...

Reflecting on results...

                                       Round 20 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  20 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   1 │
│ simulated             │                                                                   1 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   1 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                           466.74909 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 21/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (1)

  [01] reverse(ts_delta(close, 25)) * ts_mean(ts_delta(returns, 5) < ts_quantile(ts_delta(returns, 5), 20), 20)

Simulating 1 expressions on WQB...

Reflecting on results...

                                       Round 21 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  21 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   1 │
│ simulated             │                                                                   1 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   1 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          546.845738 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 22/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (1)

  [01] reverse(zscore(ts_sum(log(1 + returns), 40))) * inverse(ts_std_dev(returns, 20)) * sqrt(adv20)

Simulating 1 expressions on WQB...

Reflecting on results...

                                       Round 22 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  22 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   1 │
│ simulated             │                                                                   1 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   1 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          520.750245 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 23/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 23 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  23 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          268.627116 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 24/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 24 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  24 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          231.961774 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 25/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (2)

  [01] winsorize(reverse(ts_zscore(ts_sum(returns, 60), 20)), std=3)

  [02] group_zscore(reverse(ts_delta(close, 30) / ts_delay(close, 30)) * sqrt(inverse(cap)),
group=bucket(rank(cap), range='0,1,0.2'))

Simulating 2 expressions on WQB...

2026-04-22 05:42:44 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full="group_zscore(reverse(ts_delta(close, 30) / ts_delay(close, 30)) * sqrt(inverse(cap)), group=bucket(rank(cap), range='0,1,0.2'))"

Reflecting on results...

                                       Round 25 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  25 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   2 │
│ simulated             │                                                                   1 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   1 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          549.067594 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 26/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (2)

  [01] reverse(ts_zscore(ts_delta(vwap, 5), 15)) * ts_scale(high - low, 15)

  [02] if_else(ts_sum(returns,5) < -0.1, reverse(ts_sum(returns,5)) * 2, reverse(ts_sum(returns,5)))

Simulating 2 expressions on WQB...

Reflecting on results...

                                       Round 26 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  26 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   2 │
│ simulated             │                                                                   2 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   2 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                           539.70385 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 27/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (1)

  [01] quantile(reverse(ts_delta(vwap, 50) / ts_delay(vwap, 50)) * if_else(ts_delta(volume, 10) < 0,
ts_rank(volume, 20), 1))

Simulating 1 expressions on WQB...

Reflecting on results...

                                       Round 27 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  27 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   1 │
│ simulated             │                                                                   1 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   1 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          477.582559 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 28/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 0 expressions

No expressions passed novelty filter.

                                       Round 28 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  28 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                   0 │
│ expressions_generated │                                                                   0 │
│ after_validation      │                                                                   0 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          125.152598 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 29/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (1)

  [01] if_else(returns < 0, multiply(reverse(returns), divide(volume, adv20)), multiply(reverse(returns),
divide(volume, adv20)) * 0.5)

Simulating 1 expressions on WQB...

Reflecting on results...

                                       Round 29 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  29 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   1 │
│ simulated             │                                                                   1 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   1 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                            325.7805 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 30/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 30 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  30 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          251.419653 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 31/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 31 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  31 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          224.988461 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 32/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (2)

  [01] multiply(reverse(ts_mean(returns, 10)), sqrt(cap))

  [02] ( -ts_delta(close, 20) * ( 1 - ( (close - kth_element(low, 20, k=1, ignore='NaN')) / (kth_element(high, 20,
k=20, ignore='NaN') - kth_element(low, 20, k=1, ignore='NaN') + 0.001) ) ) ) * rank(cap)

Simulating 2 expressions on WQB...

Reflecting on results...

                                       Round 32 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  32 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   2 │
│ simulated             │                                                                   2 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   2 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          633.544148 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 33/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (1)

  [01] multiply(subtract(group_mean(ts_sum(returns, 10), 1, 'subindustry'), ts_sum(returns, 10)), subtract(1,
group_rank(cap, 'subindustry')))

Simulating 1 expressions on WQB...

2026-04-22 06:31:19 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full="multiply(subtract(group_mean(ts_sum(returns, 10), 1, 'subindustry'), ts_sum(returns, 10)), subtract(1, group_rank(cap, 'subindustry')))"

Reflecting on results...

                                       Round 33 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  33 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   1 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          277.111585 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 34/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 34 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  34 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          274.626223 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 35/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 35 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  35 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          230.437531 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 36/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (1)

  [01] kth_element(returns, 10, 0) * ts_av_diff(close, 5) / ts_std_dev(returns, 10)

Simulating 1 expressions on WQB...

2026-04-22 06:43:25 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full='kth_element(returns, 10, 0) * ts_av_diff(close, 5) / ts_std_dev(returns, 10)'

Reflecting on results...

                                       Round 36 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  36 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   1 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          220.691771 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 37/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (3)

  [01] reverse(ts_zscore(open - close, 10))

  [02] reverse(ts_delta(open - close, 5))

  [03] divide(reverse(ts_delta(returns, 60)), ts_zscore(power(ts_delta(returns, 20), 3), 120))

Simulating 3 expressions on WQB...

Reflecting on results...

                                       Round 37 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  37 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   3 │
│ simulated             │                                                                   3 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   3 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                            732.4852 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 38/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (1)

  [01] reverse(ts_regression(returns, divide(volume, sharesout), 40, rettype=1))

Simulating 1 expressions on WQB...

Reflecting on results...

                                       Round 38 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  38 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   1 │
│ simulated             │                                                                   1 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   1 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                           480.20681 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 39/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 39 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  39 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          217.011348 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 40/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (1)

  [01] multiply(divide(ts_decay_linear(reverse(returns), 60), max(ts_std_dev(returns, 25), 0.0001)), power(cap,
0.5))

Simulating 1 expressions on WQB...

Reflecting on results...

                                       Round 40 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  40 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   1 │
│ simulated             │                                                                   1 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   1 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          443.730542 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 41/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 41 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  41 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          239.046863 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 42/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 42 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  42 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          286.514214 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 43/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (4)

  [01] if_else(ts_delta(returns, 60) < 0, reverse(ts_delta(returns, 60)) * group_zscore(cap, 'large'), 0)

  [02] multiply(if_else(ts_quantile(returns, 40) < 0.5, -1, 1), normalize(subtract(ts_product(add(1, returns), 40),
1)))

  [03] if_else(ts_zscore(returns, 40) < 0, reverse(zscore(subtract(ts_product(add(1, returns), 30), 1))), 0)

  [04] subtract(ts_zscore(ts_sum(returns, 50), 252), ts_zscore(ts_sum(returns, 3), 252))

Simulating 4 expressions on WQB...

2026-04-22 07:28:10 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full="if_else(ts_delta(returns, 60) < 0, reverse(ts_delta(returns, 60)) * group_zscore(cap, 'large'), 0)"

Reflecting on results...

                                       Round 43 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  43 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   4 │
│ simulated             │                                                                   3 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   3 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          758.549047 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 44/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 44 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  44 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          325.235394 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 45/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (2)

  [01] subtract(group_mean(ts_sum(returns,3), cap, subindustry), ts_sum(returns,3))

  [02] ts_delta(reverse(group_mean(ts_sum(returns,1), cap, subindustry)), 3)

Simulating 2 expressions on WQB...

Reflecting on results...

                                       Round 45 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  45 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   2 │
│ simulated             │                                                                   2 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   2 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          595.682419 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 46/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 31 expressions

Expressions after novelty filter (4)

  [01] if_else(ts_sum(returns, 40) < 0, -1 * zscore(ts_delta(volume, 20)), 0)

  [02] if_else(ts_sum(returns, 20) < 0, -1 * zscore(ts_zscore(volume, 20)), 0)

  [03] if_else(and(abs(ts_sum(returns,20)) > multiply(2, ts_std_dev(returns,20)), not(or(close >
add(ts_max(high,20), multiply(0.5, ts_std_dev(returns,20))), close < subtract(ts_min(low,20), multiply(0.5,
ts_std_dev(returns,20)))))), 1, if_else(and(abs(ts_sum(returns,20)) > multiply(2, ts_std_dev(returns,20)), or(close
> add(ts_max(high,20), multiply(0.5, ts_std_dev(returns,20))), close < subtract(ts_min(low,20), multiply(0.5,
ts_std_dev(returns,20))))), -1, 0))

  [04] if_else(and(abs(ts_sum(returns,20)) > multiply(2, ts_std_dev(returns,20)), not(or(close >
add(ts_max(high,20), multiply(0.5, ts_std_dev(returns,20))), close < subtract(ts_min(low,20), multiply(0.5,
ts_std_dev(returns,20)))))), 1, if_else(and(abs(ts_sum(returns,20)) > multiply(2, ts_std_dev(returns,20)), or(close
> add(ts_max(high,20), multiply(0.5, ts_std_dev(returns,20))), close < subtract(ts_min(low,20), multiply(0.5,
ts_std_dev(returns,20)))), volume < ts_mean(volume,20)), -2, if_else(and(abs(ts_sum(returns,20)) > multiply(2,
ts_std_dev(returns,20)), or(close > add(ts_max(high,20), multiply(0.5, ts_std_dev(returns,20))), close <
subtract(ts_min(low,20), multiply(0.5, ts_std_dev(returns,20)))), not(volume < ts_mean(volume,20))), -1, 0)))

Simulating 4 expressions on WQB...

2026-04-22 08:01:17 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full='if_else(and(abs(ts_sum(returns,20)) > multiply(2, ts_std_dev(returns,20)), not(or(close > add(ts_max(high,20), multiply(0.5, ts_std_dev(returns,20))), close < subtract(ts_min(low,20), multiply(0.5, ts_std_dev(returns,20)))))), 1, if_else(and(abs(ts_sum(returns,20)) > multiply(2, ts_std_dev(returns,20)), or(close > add(ts_max(high,20), multiply(0.5, ts_std_dev(returns,20))), close < subtract(ts_min(low,20), multiply(0.5, ts_std_dev(returns,20))))), -1, 0))'
2026-04-22 08:01:24 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full='if_else(and(abs(ts_sum(returns,20)) > multiply(2, ts_std_dev(returns,20)), not(or(close > add(ts_max(high,20), multiply(0.5, ts_std_dev(returns,20))), close < subtract(ts_min(low,20), multiply(0.5, ts_std_dev(returns,20)))))), 1, if_else(and(abs(ts_sum(returns,20)) > multiply(2, ts_std_dev(returns,20)), or(close > add(ts_max(high,20), multiply(0.5, ts_std_dev(returns,20))), close < subtract(ts_min(low,20), multiply(0.5, ts_std_dev(returns,20)))), volume < ts_mean(volume,20)), -2, if_else(and(abs(ts_sum(returns,20)) > multiply(2, ts_std_dev(returns,20)), or(close > add(ts_max(high,20), multiply(0.5, ts_std_dev(returns,20))), close < subtract(ts_min(low,20), multiply(0.5, ts_std_dev(returns,20)))), not(volume < ts_mean(volume,20))), -1, 0)))'

Reflecting on results...

                                       Round 46 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  46 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  31 │
│ expressions_generated │                                                                  31 │
│ after_validation      │                                                                  31 │
│ after_novelty_filter  │                                                                   4 │
│ simulated             │                                                                   2 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   2 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          677.231841 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 47/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 47 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  47 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          237.543446 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 48/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 48 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  48 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          275.844972 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 49/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

Expressions after novelty filter (2)

  [01] if_else(ts_regression(volume, ts_step(1), 30, rettype=1) < 0, -ts_delta(close, 30) / ts_delay(close, 30), 0)

  [02] if_else(ts_mean(returns, 40) < ts_median(returns, 40), normalize(ts_delta(vwap, 40)), 0)

Simulating 2 expressions on WQB...

2026-04-22 08:18:07 WARNING alpha_agent.wqb_client: [WQBClient] Simulation polling timed out expr_full='if_else(ts_mean(returns, 40) < ts_median(returns, 40), normalize(ts_delta(vwap, 40)), 0)'

Reflecting on results...

                                       Round 49 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  49 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   2 │
│ simulated             │                                                                   1 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   1 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          471.360998 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────── Round 50/50 — medium-horizon reversal with liquidity and volatility normalization ────────────────

Allocation — explorer=32 | skeleton=0

[Explorer] Generating 8 ideas...

[Explorer] Synthesizing 4 variants/idea...

[Explorer] Generated 32 expressions

No expressions passed novelty filter.

                                       Round 50 Summary
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Metric                ┃                                                               Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ round                 │                                                                  50 │
│ direction             │ medium-horizon reversal with liquidity and volatility normalization │
│ ideas                 │                                                                  32 │
│ expressions_generated │                                                                  32 │
│ after_validation      │                                                                  32 │
│ after_novelty_filter  │                                                                   0 │
│ simulated             │                                                                   0 │
│ qualified             │                                                                   0 │
│ soft_qualified        │                                                                   0 │
│ skeletons_added       │                                                                   0 │
│ pass_rate             │                                                                 0.0 │
│ explorer_simulated    │                                                                   0 │
│ explorer_qualified    │                                                                   0 │
│ skeleton_simulated    │                                                                   0 │
│ skeleton_qualified    │                                                                   0 │
│ duration_s            │                                                          285.828481 │
└───────────────────────┴─────────────────────────────────────────────────────────────────────┘

──────────────────────────────────────────────── Session Complete ─────────────────────────────────────────────────

Total rounds: 50 | Simulated: 64 | Qualified: 0 | Pass rate: 0.0%

## 4. Review results

In [5]:
import pandas as pd

summary_rows = [r.to_dict() for r in reports]
df_summary = pd.DataFrame(summary_rows)
print("Round-by-round summary:")
display(df_summary)

Round-by-round summary:

,round,direction,ideas,expressions_generated,after_validation,after_novelty_filter,simulated,qualified,soft_qualified,skeletons_added,pass_rate,explorer_simulated,explorer_qualified,skeleton_simulated,skeleton_qualified,duration_s
0,1,medium-horizon reversal with liquidity and vol...,32,32,32,22,21,0,0,0,0.0,21,0,0,0,3640.740633
1,2,medium-horizon reversal with liquidity and vol...,32,32,32,6,3,0,0,0,0.0,3,0,0,0,789.935610
2,3,medium-horizon reversal with liquidity and vol...,32,32,32,2,2,0,0,0,0.0,2,0,0,0,708.227617
3,4,medium-horizon reversal with liquidity and vol...,30,30,30,0,0,0,0,0,0.0,0,0,0,0,324.262349
4,5,medium-horizon reversal with liquidity and vol...,32,32,32,4,4,0,0,0,0.0,4,0,0,0,870.271694
5,6,medium-horizon reversal with liquidity and vol...,32,32,32,5,2,0,0,0,0.0,2,0,0,0,804.020176
6,7,medium-horizon reversal with liquidity and vol...,32,32,32,1,1,0,0,0,0.0,1,0,0,0,540.225610
7,8,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,305.583408
8,9,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,348.484541
9,10,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,394.115372
10,11,medium-horizon reversal with liquidity and vol...,29,29,29,4,2,0,0,0,0.0,2,0,0,0,682.993373
11,12,medium-horizon reversal with liquidity and vol...,32,32,32,1,0,0,0,0,0.0,0,0,0,0,305.210313
12,13,medium-horizon reversal with liquidity and vol...,32,32,32,1,1,0,0,0,0.0,1,0,0,0,538.661950
13,14,medium-horizon reversal with liquidity and vol...,32,32,32,1,1,0,0,0,0.0,1,0,0,0,493.259648
14,15,medium-horizon reversal with liquidity and vol...,32,32,32,2,2,0,0,0,0.0,2,0,0,0,622.110120
15,16,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,299.378742
16,17,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,273.856673
17,18,medium-horizon reversal with liquidity and vol...,32,32,32,2,2,0,0,0,0.0,2,0,0,0,612.106674
18,19,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,252.687480
19,20,medium-horizon reversal with liquidity and vol...,32,32,32,1,1,0,0,0,0.0,1,0,0,0,466.749090
20,21,medium-horizon reversal with liquidity and vol...,32,32,32,1,1,0,0,0,0.0,1,0,0,0,546.845738
21,22,medium-horizon reversal with liquidity and vol...,32,32,32,1,1,0,0,0,0.0,1,0,0,0,520.750245
22,23,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,268.627116
23,24,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,231.961774
24,25,medium-horizon reversal with liquidity and vol...,32,32,32,2,1,0,0,0,0.0,1,0,0,0,549.067594
25,26,medium-horizon reversal with liquidity and vol...,32,32,32,2,2,0,0,0,0.0,2,0,0,0,539.703850
26,27,medium-horizon reversal with liquidity and vol...,32,32,32,1,1,0,0,0,0.0,1,0,0,0,477.582559
27,28,medium-horizon reversal with liquidity and vol...,0,0,0,0,0,0,0,0,0.0,0,0,0,0,125.152598
28,29,medium-horizon reversal with liquidity and vol...,32,32,32,1,1,0,0,0,0.0,1,0,0,0,325.780500
29,30,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,251.419653
30,31,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,224.988461
31,32,medium-horizon reversal with liquidity and vol...,32,32,32,2,2,0,0,0,0.0,2,0,0,0,633.544148
32,33,medium-horizon reversal with liquidity and vol...,32,32,32,1,0,0,0,0,0.0,0,0,0,0,277.111585
33,34,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,274.626223
34,35,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,230.437531
35,36,medium-horizon reversal with liquidity and vol...,32,32,32,1,0,0,0,0,0.0,0,0,0,0,220.691771
36,37,medium-horizon reversal with liquidity and vol...,32,32,32,3,3,0,0,0,0.0,3,0,0,0,732.485200
37,38,medium-horizon reversal with liquidity and vol...,32,32,32,1,1,0,0,0,0.0,1,0,0,0,480.206810
38,39,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,217.011348
39,40,medium-horizon reversal with liquidity and vol...,32,32,32,1,1,0,0,0,0.0,1,0,0,0,443.730542
40,41,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,239.046863
41,42,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,286.514214
42,43,medium-horizon reversal with liquidity and vol...,32,32,32,4,3,0,0,0,0.0,3,0,0,0,758.549047
43,44,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,325.235394
44,45,medium-horizon reversal with liquidity and vol...,32,32,32,2,2,0,0,0,0.0,2,0,0,0,595.682419
45,46,medium-horizon reversal with liquidity and vol...,31,31,31,4,2,0,0,0,0.0,2,0,0,0,677.231841
46,47,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,237.543446
47,48,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,275.844972
48,49,medium-horizon reversal with liquidity and vol...,32,32,32,2,1,0,0,0,0.0,1,0,0,0,471.360998
49,50,medium-horizon reversal with liquidity and vol...,32,32,32,0,0,0,0,0,0.0,0,0,0,0,285.828481

In [6]:
# Check alpha memory status
stats = memory.stats()
print(f"Alpha Memory after run:")
print(f"  Total:     {stats['total']}")
print(f"  Qualified: {stats['qualified']}")
print(f"  Pass rate: {stats['pass_rate']:.1%}")

Alpha Memory after run:
  Total:     80
  Qualified: 0
  Pass rate: 0.0%

In [7]:
# View top qualified alphas
top = memory.top_by_metric('sharpe', k=5, qualified_only=True)
print("Top 5 qualified alphas by Sharpe:")
for a in top:
    m = a['metrics']
    print(f"  sharpe={m.get('sharpe',0):.3f} fitness={m.get('fitness',0):.3f}")
    print(f"  {a['expression'][:90]}")
    print()

Top 5 qualified alphas by Sharpe:

In [8]:
# View recent reflections (learning)
recent = memory.recent(n=10)
failed = [a for a in recent if not a['qualified'] and a['reflection']]

print("Recent failure reflections:")
for a in failed[:3]:
    print(f"\n  Expression: {a['expression'][:60]}")
    print(f"  Reflection: {str(a['reflection'])[:300]}")

Recent failure reflections:

  Expression: if_else(ts_regression(volume, ts_step(1), 30, rettype=1) < 0
  Reflection: ```json
{
  "root_cause": "The alpha suffers from near-zero predictive power (IC = 0) due to ineffective signal construction, coupled with extreme concentration from a sparse binary condition. The 30-day reversal signal with volume confirmation fails to generate meaningful forecasts, likely because

  Expression: if_else(ts_sum(returns, 20) < 0, -1 * zscore(ts_zscore(volum
  Reflection: {
  "root_cause": "The alpha expression fails due to a lack of predictive power and high turnover, primarily caused by a binary if_else condition that only activates for past losers, combined with an overcomplicated and ineffective volume signal. The near-zero IC mean (-0.000) indicates no correlati

  Expression: if_else(ts_sum(returns, 40) < 0, -1 * zscore(ts_delta(volume
  Reflection: {
  "root_cause": "The alpha lacks predictive power due to noisy and non-predictive signals, primarily caused by using raw volume delta without sector-relative normalization, binary conditioning leading to sparse and concentrated positions, and misaligned windows that result in high turnover and zer

## 5. Skeleton Registry — Results

In [9]:
# Skeleton registry stats after the run
reg_stats = registry.stats()
print("Skeleton Registry Stats:")
for k, v in reg_stats.items():
    print(f"  {k}: {v}")

# Show all active skeletons
skeletons = registry.all()
print(f"\nActive skeletons: {len(skeletons)}")
for sk in skeletons[:10]:
    print(f"\n  [{sk.skeleton_id[:8]}] {sk.template_str[:80]}")
    print(f"    operators: {sk.operators_used}")
    print(f"    field_slots: {[s['name'] for s in sk.field_slots]}")
    print(f"    attempts={sk.attempt_count}  qualified={sk.success_count}  rate={sk.success_rate:.0%}")

Skeleton Registry Stats:
  total: 0
  active: 0
  instances: 0

Active skeletons: 0

In [10]:
# TrackBandit stats
from alpha_agent.search.track_bandit import TrackBandit
bandit = TrackBandit(skeleton_registry=registry)
# Show allocation preview for different budgets
for budget in [5, 10, 20]:
    print(bandit.allocation_preview(budget))

# Bandit stats from reports
print("\nPer-round track performance:")
import pandas as pd
track_rows = []
for r in reports:
    track_rows.append({
        "round": r.round_num,
        "explorer_sim": r.explorer_simulated,
        "explorer_qual": r.explorer_qualified,
        "skeleton_sim": r.skeleton_simulated,
        "skeleton_qual": r.skeleton_qualified,
        "skeletons_added": r.skeletons_added,
    })
df_tracks = pd.DataFrame(track_rows)
display(df_tracks)

Budget=5: explorer=5 (100%) | skeleton=0 (0%)
Budget=10: explorer=10 (100%) | skeleton=0 (0%)
Budget=20: explorer=20 (100%) | skeleton=0 (0%)

Per-round track performance:

,round,explorer_sim,explorer_qual,skeleton_sim,skeleton_qual,skeletons_added
0,1,21,0,0,0,0
1,2,3,0,0,0,0
2,3,2,0,0,0,0
3,4,0,0,0,0,0
4,5,4,0,0,0,0
5,6,2,0,0,0,0
6,7,1,0,0,0,0
7,8,0,0,0,0,0
8,9,0,0,0,0,0
9,10,0,0,0,0,0
10,11,2,0,0,0,0
11,12,0,0,0,0,0
12,13,1,0,0,0,0
13,14,1,0,0,0,0
14,15,2,0,0,0,0
15,16,0,0,0,0,0
16,17,0,0,0,0,0
17,18,2,0,0,0,0
18,19,0,0,0,0,0
19,20,1,0,0,0,0
20,21,1,0,0,0,0
21,22,1,0,0,0,0
22,23,0,0,0,0,0
23,24,0,0,0,0,0
24,25,1,0,0,0,0
25,26,2,0,0,0,0
26,27,1,0,0,0,0
27,28,0,0,0,0,0
28,29,1,0,0,0,0
29,30,0,0,0,0,0
30,31,0,0,0,0,0
31,32,2,0,0,0,0
32,33,0,0,0,0,0
33,34,0,0,0,0,0
34,35,0,0,0,0,0
35,36,0,0,0,0,0
36,37,3,0,0,0,0
37,38,1,0,0,0,0
38,39,0,0,0,0,0
39,40,1,0,0,0,0
40,41,0,0,0,0,0
41,42,0,0,0,0,0
42,43,3,0,0,0,0
43,44,0,0,0,0,0
44,45,2,0,0,0,0
45,46,2,0,0,0,0
46,47,0,0,0,0,0
47,48,0,0,0,0,0
48,49,1,0,0,0,0
49,50,0,0,0,0,0

In [11]:
# Release long-lived objects that hold DB/file handles
import gc

for obj_name in ["memory", "registry", "store"]:
    obj = globals().get(obj_name)
    close_fn = getattr(obj, "close", None)
    if callable(close_fn):
        try:
            close_fn()
            print(f"Closed: {obj_name}")
        except Exception as e:
            print(f"Failed to close {obj_name}: {e}")

for obj_name in ["memory", "registry", "store"]:
    if obj_name in globals():
        del globals()[obj_name]

gc.collect()
print("Released DB/file handles and cleared related globals.")

Closed: memory
Closed: registry
Released DB/file handles and cleared related globals.

## 6. Release DB handles (optional but recommended)

Run this cell after finishing Notebook 04 to release DuckDB file locks without restarting the kernel.

## ✅ Notebook 04 Complete

The dual-track closed loop has run. The system has:
- **Explorer track**: Generated LLM hypotheses guided by RAG context, synthesized expressions
- **Skeleton track**: Retrieved proven skeleton templates, generated field-substituted variants
- **TrackBandit**: Adaptively allocated simulation budget between both tracks
- **SkeletonExtractor**: Deposited qualified/soft-qualified alphas back into SkeletonRegistry
- Filtered near-duplicates (strict novelty for Explorer, field_coverage for Skeleton)
- Reflected on failures and stored insights for next round

**Next**: `05_results_and_novelty_analysis.ipynb` for full analysis with skeleton family trees.

## ✅ Notebook 04 Complete

The closed loop has run. The system has:
- Generated LLM hypotheses guided by RAG context
- Synthesized and locally validated expressions
- Filtered out near-duplicates using novelty scoring
- Submitted to WQB for backtesting
- Reflected on failures and stored insights for next round

**Next**: `05_results_and_novelty_analysis.ipynb` for full analysis.